version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    # run backend test everytime when container is loaded or started
    command: npm test
    ports:
      - '9000:9000'
    environment:
      APPID: '22313e921b28d2559ab79166c0f9b6d2'

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    # volumes needed for hot reloading functionality
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
